### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string

### ISSUE THREAD

**Issue by VickyKoblinski** [itaditya/storybook-addon-variants#3]
Hey! I need to give a shoutout, I love this plugin.

I initally had some trouble with it where it was freezing up my pages pretty badly. I'm also using storybook-addon-apollo-client and all my components are wrapped with a chakra UI provider, so I guess it was just a lot to load in. I moved this plugin to the top of my addons array and it sped everything up by a ton.

The problem I'm running into now is unrelated. Booting up storybook, I get this:

```
info => Loading presets
WARN   Failed to load preset: {"type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:998:3)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10)
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:998:3)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/Users/vickykoblinski/projects/spacedust/app/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```

Storybook still boots and everything appears to be working, so I don't know, but I did narrow this down to this plugin. The error goes away when I remove this plugin.

**Comment by wiktusser** [comment]
@VickyKoblinski I have similar issue and the variants extenstion doesnt seem to be working for me with this error (storybook still boots up)
